remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
title: Scistats
description: High-performance statistics

search_enabled: true

aux_links:
  "Scistats on GitHub":
    - "//github.com/alandefreitas/scistats"

footer_content: "Copyright &copy; Alan Freitas. Distributed by an <a href=\"https://github.com/alandefreitas/scistats/tree/master/LICENSE.txt\">MIT license.</a>"
